// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMY52CetBc3273cfh1u9pSZpopLoGJZI',
    appId: '1:799408140068:web:b6e7101817b5a1c628cdb1',
    messagingSenderId: '799408140068',
    projectId: 'flutter-expense-tracker-393fc',
    authDomain: 'flutter-expense-tracker-393fc.firebaseapp.com',
    storageBucket: 'flutter-expense-tracker-393fc.firebasestorage.app',
    measurementId: 'G-025ZLZDESZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZqqeDvIKnVPY960UrpbqOUEQBe0bQmY',
    appId: '1:799408140068:android:bd5c9e84f80d05c128cdb1',
    messagingSenderId: '799408140068',
    projectId: 'flutter-expense-tracker-393fc',
    storageBucket: 'flutter-expense-tracker-393fc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDE1uKzB7uJPn-vvW6Kq6phXT9fJRSrTc',
    appId: '1:799408140068:ios:a60244ad208c8a9128cdb1',
    messagingSenderId: '799408140068',
    projectId: 'flutter-expense-tracker-393fc',
    storageBucket: 'flutter-expense-tracker-393fc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDE1uKzB7uJPn-vvW6Kq6phXT9fJRSrTc',
    appId: '1:799408140068:ios:a60244ad208c8a9128cdb1',
    messagingSenderId: '799408140068',
    projectId: 'flutter-expense-tracker-393fc',
    storageBucket: 'flutter-expense-tracker-393fc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAMY52CetBc3273cfh1u9pSZpopLoGJZI',
    appId: '1:799408140068:web:993005f33a3cc74828cdb1',
    messagingSenderId: '799408140068',
    projectId: 'flutter-expense-tracker-393fc',
    authDomain: 'flutter-expense-tracker-393fc.firebaseapp.com',
    storageBucket: 'flutter-expense-tracker-393fc.firebasestorage.app',
    measurementId: 'G-WW38RWJQNB',
  );
}
